import Head from 'next/head'
import styles from "../styles/Home.module.css";
import { getAllPost } from '../lib/posts';
import Image from 'next/image';
import Link from 'next/link';


export default function Home() {

  const posts = getAllPost()

  return (
    <>
      <Head>
        <title>Next Gen Coders</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Next Gen Coders</h1>
        <div>
          {posts.map((post) => (
            <BlogPostPreview key={post.id} data={post} />
          ))}
        </div>
      </main>
    </>
  )
}

const BlogPostPreview = (props) => {
  const { data } = props;
  return (
    <div className='max-w-[400px]'>
      <Image src={data.coverImage} width={400} height={200} />
      <h2>
        <Link legacyBehavior href={`/blog-post/${data.slug}`}>
          <a className='no-underline text-black'>{data.title}</a>
        </Link>
      </h2>
      <div>{data.publishDate}</div>
      <p>{data.excerpt}</p>
      <div style={{ fontWeight: "bold" }}>{data.author}</div>
    </div>
  );
};


